Add missing routes
It seems we forgot to add the routes for the associated records path in
the has_many association. This commit adds the necessary routes to
ensure that the associated records can be accessed correctly.

Without these routes, the consumer application could be throwing a
NoMethodError:

> Information for cause: NoMethodError (undefined method 'has_many_associated_records_path' for an instance of ActionDispatch::Routing::RoutesProxy):
>
> actionpack (8.1.3.1) lib/action_dispatch/routing/routes_proxy.rb:47:in 'ActionDispatch::Routing::RoutesProxy#method_missing'
> uchi (0.3.0) app/components/uchi/field/has_many/edit.html.erb:173:in 'Uchi::Field::HasMany::Edit#call'
> view_component (4.12.0) lib/view_component/template.rb:166:in 'block in ViewComponent::Template#safe_method_name_call'