Make redirects to same URL work in Firefox
When submitting a form that redirects to the same URL, we'd get an error
from Hotwired/Turbo in Firefox:

> Error: Form responses must redirect to another location

Adding a unique query parameter to the redirect URL to prevent caching
issues in Firefox.

The reproduction for this is...

1. Go to edit a model, fx a MeetingRoom at /uchi/meeting_rooms/42/edit
2. Submit the form with POST /uchi/meeting_rooms/42
3. The controller does a redirect_to to the same URL
   /uchi/meeting_rooms/42, which is the show action.
4. In Firefox, Turbo raises the above error.